### ISSUE TITLE
The Specified Key already exists

### ISSUE THREAD

**Issue by psherwood** [DougHennig/ProjectExplorer#29] opened 2017-08-14 20:42 UTC
Doug,

I can open my project fine the 1st time but the next time I go to open it I get the error "The specified Key already exists" in the Main.prg

The code that gets it is:

_screen.oProjectExplorers.Add(loProjectExplorer, ;
   loProjectExplorer.cSolutionFolder)

To open the project again I have to delete the solutions.xml and all the metadata tables.

I've found that it only happens if I go to Version Control and enable it to use Git and then pick my repository. It puts check marks by all my source in the Project Explorer but if I exit Project Explorer it won't open again. It either gets the above error or just flashes.

**Comment by DougHennig** [comment] 2017-08-15 18:53
Hi Phil.

I can't reproduce this. It looks like Project Explorer isn't closing properly so a reference to it is still in the collection. After closing Project Explorer, type:

wait window _screen.oprojectexplorers.Count

What do you get? I get 0, meaning there's no reference to any Project Explorer open. I suspect you'll get 1.

Doug

**Comment by psherwood** [comment] 2017-08-15 21:18
Hey Doug,

The wait window gives me a zero count.

I've created a video showing you the behavior. I can recreate it every time.  

Let me know what else you need.

Here's the video: https://drive.google.com/a/sherware.com/file/d/0B_hH-UfUHNXVNlhRQ2xsUUZKeTQ/view?usp=sharing

**Comment by DougHennig** [comment] 2017-08-16 14:55
Thanks for the video. It looks like launching Project Explorer from a project hook is causing the problem: I get a little different but still anomalous behavior when I do that. I'll look into it.

**Comment by DougHennig** [comment] 2017-08-16 15:23
Yup, that's definitely the culprit. When I tested the project hook, I did it with a project that didn't use version control so that's why I didn't see this behavior before. The issue is that in order to get the version control status of the files in the project, Project Explorer has to temporarily close the project. Doing that causes the project hook to close, which causes the startup code for Project Explorer to stop, leaving the form in limbo.

I'll remove references to the project hook in the white paper and the sample project hook from the project files. Personally, I launch Project Explorer from a Thor hot key, Ctrl+Alt+P.

Thanks for your help tracking this down.

**Closed as completed by DougHennig** 2017-08-16 15:23 UTC
