### ISSUE TITLE
Tags dropdown doesn't refresh

### ISSUE THREAD

**Issue by paulmrozowski** [DougHennig/ProjectExplorer#1] opened 2017-05-24 16:07 UTC
The Tags dropdown doesn't refresh after you've added new tags via the Tag Editor. You have to close ProjectExplorer then re-open it.

**Comment by DougHennig** [comment] 2017-05-24 17:06
I'm not seeing that. I selected a class, looked at the tags in the Tags combobox, chose Tag Editor from the File menu, added a tag, closed the Tag Editor, and clicked the arrow for the combobox; the new tag is in the list. I then chose Tag Editor, removed the tag and closed, and the tag no longer appears in the combobox.

Do you have a different set of steps to reproduce?

**Comment by paulmrozowski** [comment] 2017-05-24 17:11
Run ProjectManager. Click on File > Tag Editor. Add a new tag. Close tag editor window. The new tag isn't in the dropdown.

**Comment by DougHennig** [comment] 2017-05-24 19:57
Still can't reproduce. Let me know if you still see this in the next commit.

**Comment by paulmrozowski** [comment] 2017-05-24 22:58
I just tried this on a new machine. 

- Did a clone into a folder (then pull after your last check-in). 
- Compiled as an app. 
- CD'd into the ProjectExplorer folder. 
- Opened the project, built it as an APP. 
- Then DO ProjectExplorer.APP. 
- Clicked Cancel to both prompts for Fox2bin.
- Switched the file type to project, opened an existing project.
- Clicked on File > Tag Editor
- Clicked Add
- Typed in the name of a new tag.
- Hit Enter
- Closed the Tag Editor window.
- Dropdown filter still doesn't have new tags.

![image](https://cloud.githubusercontent.com/assets/1640831/26429065/dd3353c4-40b2-11e7-9440-3609fde95d15.png)

![image](https://cloud.githubusercontent.com/assets/1640831/26429074/e8bafd46-40b2-11e7-8131-76959fe7c2f2.png)

**Comment by DougHennig** [comment] 2017-05-25 01:48
Ah, we're talking about different comboboxes -- I meant the one in the properties page for an item. I'll make the tag filter combobox update as well.

**Comment by DougHennig** [comment] 2017-05-25 19:36
This is fixed in the latest commit.

**Closed as completed by DougHennig** 2017-05-25 19:36 UTC
