### ISSUE TITLE
deleting a previously added vcx

### ISSUE THREAD

**Issue by lscheffler** [DougHennig/ProjectExplorer#92] opened 2017-11-23 20:13 UTC
To test issue #67, I've used cmdNew to create a vcx.

trying to delete it raises messagebox:
---------------------------
JSS_Projekt
---------------------------
Error #:     9
Message:     Data type mismatch.
Code:        lnValue = MessageBoxEx(lcMessage, '?', This.Caption, '&Remove,&Delete,&Cancel')
Line #:      44
Method:      projectexplorerformdesktop_52E19AZXS.removeitem

Choose Yes to display the debugger, No to continue without the debugger, or Cancel to cancel execution
---------------------------
Ja   Nein   Abbrechen   
---------------------------

**Comment by DougHennig** [comment] 2017-11-23 20:51
I cannot reproduce this. When this error occurs, choose Yes to display the Debugger and in the Debugger, find out what loItem.Type is; it should be "V" (for class library). Also, loItem.RemovePrompt should be "Do you want to remove the file from the project or delete it from the disk?" or at least some string. What do those two properties contain?

**Comment by lscheffler** [comment] 2017-11-23 21:08
The properties are set as you mentioned. Visible via locals and tooltiptext.

What I see is, 
DISPLAY STATUS shows

API library                           Instance Handle
c:\...\jvp\vfp2c32.fll                268435456
...
MessageBoxEx ...

Eventually I have an older version of vfp2c32.fll in my commonfiles folder. This is active by something else.
This might be an expensive problem to solve. I know I have done something to c32 a decade ago or so and never touched it ....
I will give it a new try the next day.

**Comment by DougHennig** [comment] 2017-11-23 21:34
Thanks for the details: it was a naming conflict between a VFP2C32 function and a PRG named MessageBoxEx in Project Explorer; I never would have found that if you had not mentioned it! Fixed in the latest release.

**Closed as completed by DougHennig** 2017-11-23 21:34 UTC
Labels: bug
