### ISSUE TITLE
Get Error Message "Unknown member oProject"

### ISSUE THREAD

**Issue by UlfNeugebauer** [DougHennig/ProjectExplorer#119] opened 2018-01-22 10:51 UTC
After editing a window, I sometimes get this message when I close it. What could that be?

![error-projektexplorer](https://user-images.githubusercontent.com/35687328/35217037-b0159618-ff61-11e7-87f5-310358b93d44.PNG)
![projektexplorer-debug](https://user-images.githubusercontent.com/35687328/35217050-bbacf278-ff61-11e7-827c-dd990a5f4656.PNG)

**Comment by DougHennig** [comment] 2018-01-22 15:11
Hi Ulf.

Are you doing CLOSE ALL or somehow closing the project? If so, that's the cause: although you cannot see it, Project Explorer opens the PJX file using MODIFY PROJECT NOWAIT NOSHOW. If you close the project using CLOSE ALL or some other means, then the reference Project Explorer has to the project in oProject is no longer valid.

Doug

**Comment by UlfNeugebauer** [comment] 2018-01-24 14:30
Hi Doug,
It did not happen here with a CLOSE ALL, but there I can see it too.
- VARTYPE( This.oProject ) = 'O'  is OK
- This.oProject.oProjectItems.Count > 0 is OK
- EMPTY( This.oProject.oProject.MainFile ) is the BUG
because
VARTYPE( This.oProject.oProject ) = 'O' is false

Ulf

**Comment by DougHennig** [comment] 2018-01-24 15:24
The oProject member of This.oProject is a reference to the VFP Project object. If the project is closed, This.oProject.oProject becomes null. So, something is closing the VFP project.

**Comment by UlfNeugebauer** [comment] 2018-01-25 09:03
Hallo Doug,

i changed the Methode CanBuildProject to:

RETURN VARTYPE( This.oProject ) = [O];
	AND This.oProject.oProjectItems.Count > 0;
	AND	VARTYPE( This.oProject.oProject ) = [O];
	AND !EMPTY( This.oProject.oProject.MainFile )

now the exception is handled.

I changed the Activate method by inserting the following code:

IF VARTYPE( ThisForm.oProject ) = [O] AND VARTYPE( ThisForm.oProject.oProject ) # [O]
	This.tmrRelease.Enabled =  .T.
ENDIF

I added a timer to the form:
Interval = 500
Enabled = .T.
Method Timer:
This.enabled = .F.
Release Thisform

Now the form closed after COSE ALL if i click on the form.
Of course it would be better if we could tie ourselves directly to the conclusion of the project.
bindevent ??

best regards

**Comment by DougHennig** [comment] 2018-01-25 18:30
I implemented something similar (but without a timer) in the latest release. However, that does not resolve the underlying problem: why is the project being closed when you edit an item?

**Comment by UlfNeugebauer** [comment] 2018-01-26 09:42
Hello Doug,
I'll watch that and then get in touch.
This message comes after running a program when i return to the VFP developer mode.

![afterrunnigprojekt](https://user-images.githubusercontent.com/35687328/35433588-ec037704-027b-11e8-9312-c47b79f7992b.PNG)

**Comment by DougHennig** [comment] 2018-01-29 15:52
That again tells me that something is causing variables to be released on your system. lcMenu is defined earlier in that method as the name of a shortcut menu (the one displayed when you click the "hamburger" button in the Project Explorer toolbar). That menu is activated, the code for the menu item you selected executed, and on return to the ShowMenu method, it checks the lcMenu variable. However that variable no longer exists, so something on your machine is doing a CLEAR ALL or RELEASE ALL. That would explain all of the error you have been getting.

**Closed as completed** 2018-05-15 19:20 UTC
