### ISSUE TITLE
git commands fail because they are case sensitive

### ISSUE THREAD

**Issue by marangonico** [DougHennig/ProjectExplorer#36] opened 2017-10-06 17:10 UTC
Running git "version 2.13.0.windows.1" on Windows 10, git commands fail because they are case sensitive.

i.e.
ProjectExplorer runs `git commit --file "C:\gitvsrc\commit.txt" "C:\gitvsrc\test\git01.prg"`, but the file is seen as git01.PRG

```
C:\gitvsrc>DIR test
 Directory di C:\gitvsrc\test

06/10/2017  18:53    <DIR>          .
06/10/2017  18:53    <DIR>          ..
06/10/2017  18:46                 3 git01.PRG

```
Creating the file from ProjectExplorer, the command takes care of filename case: `git add "C:\gitvsrc\test\git01.PRG"`

**Comment by DougHennig** [comment] 2017-10-07 20:13
VFP seems inconsistent about filename case; sometimes I see files with a “prg” extension and sometimes it’s “PRG,” and sometime a file that was “prg” is now “PRG.” Although Project Explorer has code to handle filename case, I see a couple of cases where it doesn't handle it, so I'll fix that. However, given that the filename case can change, I recommend turning off case sensitivity; use this command line directive:

git config --global core.ignorecase true

Doug

**Comment by marangonico** [comment] 2017-10-08 10:24
I already tried the ignorecase option, but it seems it doesn't work.
Here is what happens on my system.

1) I create a file using ProjectExplorer and let VFP force the extension.
* Git view
` new file:   test/git10.PRG`
* File system view:
`08/10/2017  10:11                 9 git10.PRG`
* Command issued by ProjectExplorer:
`git add "C:\gitvsrc\test\git10.PRG"`

2) I modify the file
* Git view
`modified:   test/git10.PRG`
* File system view:
`08/10/2017  12:08                12 git10.prg`
Note: After the editing, the file is seen with the lower case extension.

3) I try to commit the file and it fails
* Command issued by ProjectExplorer:
`git commit --file "C:\gitvsrc\commit.txt" "C:\gitvsrc\test\git10.prg"`
The message error returned is:
`error: pathspec 'C:\gitvsrc\test\git10.prg' did not match any file(s) known to git.`

ignorecase=true does not helps here.

As you can see the problem is the change of the extension after the modification.
If you modify the file using ProjectExplorer, the command window reports: 
MODIFY COMMAND c:\gitvsrc\test\git12.prg NOWAIT AS 1252
After that the extension is set to lower case.

Hope this helps.

**Comment by marangonico** [comment] 2017-10-08 10:35
My .git\config

[core]
	repositoryformatversion = 0
	filemode = false
	bare = false
	logallrefupdates = true
	symlinks = false
	ignorecase = true
[remote "origin"]
	url = "my repository here"
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
	remote = origin
	merge = refs/heads/master

**Comment by DougHennig** [comment] 2017-10-13 21:06
The problem is that VFP is renaming the file after it's been added to the repository. Although ignorecase=true is supposed to handle that, it looks like it doesn't always. I'm not sure what to do about that. I suppose one possibility is that after closing the file, I can check whether it has been renamed and if so, rename it back to the original name. What do you think of that?

**Comment by marangonico** [comment] 2017-10-15 10:06
Will you be able to intercept the closing of the file?
There could be other ways a file extension could change case within the VFP IDE?
I was thinking if you could check these extensions inside the git status check.. probably it is a safer place to do it? Just my 2 cents.

**Comment by DougHennig** [comment] 2017-10-15 19:46
I've been looking into this and it looks like there are two Git config files. Try this:

git config --global core.ignorecase true
git config --system core.ignorecase true

When I do both of those, Git does appear to be case-insensitive. Here is some code you can use in VFP to test it:

md c:\testcase
cd c:\testcase
modify command startup.prg && enter some text, save, and close
! git init
! git add startup.prg
! git commit -m "Initial commit"
modify command startup && notice no extension specified: when change text, save, and close, file is renamed to startup.PRG
! git status --porcelain > status.txt
modify file status && shows that startup.prg has been modified
! git commit startup.prg -m "Saved changes"
! git status --porcelain > status.txt
modify file status && shows that startup.prg is no longer modified

Doug

**Closed as completed** 2017-11-10 17:33 UTC
